steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: $(python.version)
    architecture: '$(python.architecture)'
    addToPath: true
  displayName: Use Python $(python.version)

- bash: |
    PYTHON_PATH=$(python -c 'import sys; print(sys.executable)')
    echo "##vso[task.setvariable variable=PY_EXE]$PYTHON_PATH"
  displayName: Set Python Path

- script: |
    echo '##vso[task.setvariable variable=PIPENV_DEFAULT_PYTHON_VERSION]'$(python.version)
  env:
    PYTHON_VERSION: $(python.version)

- template: install-dependencies.yml

- script: |
    python -m pip install --upgrade wheel pip setuptools twine readme_renderer[md]
    python setup.py sdist bdist_wheel
    twine check dist/*
  displayName: Build and check package
  env:
    PY_EXE: $(PY_EXE)
    GIT_SSL_CAINFO: $(GIT_SSL_CAINFO)
    LANG: $(LANG)
    PIPENV_DEFAULT_PYTHON_VERSION: $(PIPENV_DEFAULT_PYTHON_VERSION)
    PYTHONWARNINGS: ignore:DEPRECATION
    PIPENV_NOSPIN: '1'
